export interface item {
    barcode: string;
    name: string;
    description?: string;
    price: number;
    stock: number;
    unit: string;
    size: string;
    productCategory: number;
}

// create table public."Product" (
//   id bigint generated by default as identity not null,
//   created_at timestamp with time zone not null default now(),
//   barcode text null,
//   name text null,
//   price numeric null,
//   stock numeric null,
//   unit text null default ''::text,
//   size text null default ''::text,
//   "productCategory" bigint null,
//   constraint Product_pkey primary key (id),
//   constraint Product_productCategory_fkey foreign KEY ("productCategory") references "Category" (id) on update CASCADE on delete set default
// ) TABLESPACE pg_default;